name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./materialious

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm ci

      - name: Build Web
        run: npm run build

      - name: Add iOS Platform
        run: npx cap add ios

      - name: Sync Capacitor
        run: npx cap sync ios

      - name: Build Archive (Unsigned)
        run: |
          cd ios/App
          xcodebuild \
            -scheme App \
            -configuration Release \
            -archivePath $PWD/build/App.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO
    
      - name: Create IPA (Unsigned Jailbreak Version)
        run: |
          cd ios/App

          mkdir -p build/ipa/Payload

          cp -R build/App.xcarchive/Products/Applications/App.app build/ipa/Payload/

          cd build/ipa
          zip -r App.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: materialious/ios/App/build/ipa/App.ipa

